version: '3'

services:
  rabbitmq:
    image: 'bitnami/rabbitmq:latest'
    environment:
      - RABBITMQ_USERNAME=user
      - RABBITMQ_PASSWORD=password
      - RABBITMQ_VHOST=/
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - 'rabbitmq_data:/bitnami'
    networks:
      - rabbitmq-network

networks:
  rabbitmq-network:
    driver: bridge

volumes:
  rabbitmq_data:
    driver: local
